name: Update VLESS

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"  # هر 1 ساعت

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download sources
        run: |
          curl -L https://raw.githubusercontent.com/Epodonios/v2ray-configs/refs/heads/main/Splitted-By-Protocol/vless.txt -o epodonios.txt
          curl -L https://raw.githubusercontent.com/barry-far/V2ray-Config/refs/heads/main/Splitted-By-Protocol/vless.txt -o barry.txt
          cat epodonios.txt barry.txt > vless.txt

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Filter configs
        run: |
          python3 filter.py

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add output/vless.txt
          git commit -m "update vless" || exit 0
          git push
