name: Pro Gamer Mode VLESS

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
    - cron: "30 * * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y curl python3

      - name: Download configs
        run: |
          curl -L https://raw.githubusercontent.com/Epodonios/v2ray-configs/refs/heads/main/Splitted-By-Protocol/vless.txt -o epodonios.txt
          curl -L https://raw.githubusercontent.com/barry-far/V2ray-Config/refs/heads/main/Splitted-By-Protocol/vless.txt -o barry.txt

          cat epodonios.txt barry.txt > vless.txt

      - name: Run Pro Gamer AI
        run: |
          python3 filter.py

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add output/vless.txt ai_cache.json
          git commit -m "pro gamer update" || exit 0
          git push
